name: SRM Syctem
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master, develop ]
jobs:
  build:
    env:
      CI: true
      MONGO_URI: mongodb://localhost/mean_db
      JWT: test-jwt
    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ['5.0', '6.0']
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Use MongoDb from GitHub actions
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Install dependencies
        run: npm install
      - run: npm run deploy
      - run: npm run lint
      - run: npm run test
